require "user.editor"
require "user.plugins"
require "user.telescope"
require "user.theme"
require "user.treesitter"
require "user.autocomplete"
require "user.keybinds"

require "user.golang"
require "user.markdown"
require "user.clojure"
