- name: Install common tools via APT
  ansible.builtin.apt:
    pkg: 
      - btop
      - curl
      - dunst
      - feh
      - git
      - gnupg
      - htop
      - i3
      - neofetch
      - nodejs
      - npm
      - polybar
      - ripgrep
      - silversearcher-ag
      - vim
      - xclip
      - xsel
      - playerctl
    state: present
    update_cache: true
    when: ansible_pkg_mgr == 'apt'

